StirCrazy.Admin/Models/Carousel/CarouselModel.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace StirCrazy.Admin.Models.Carousel
{
    public class CarouselModel
    {
        public int Id { get; set; }
        public string FilePath { get; set; }
        public string Filename { get; set; }
        public string ContentType { get; set; }
        public string PhysicalPath { get; set; }
        public string Transition { get; set; }
        public bool IsActive { get; set; }

        public SelectList TransitionsList
        {
            get
            {
                return new SelectList(
                  new List<Object>
                {
                    new SelectListItem {Value = "sliceDown", Text = "Slice Down"},
                    new SelectListItem {Value = "sliceDownLeft", Text = "Slice Down/Left"},
                    new SelectListItem {Value = "sliceUp", Text = "Slice Up"},
                    new SelectListItem {Value = "sliceUpLeft", Text = "Slice Up/Left"},
                    new SelectListItem {Value = "sliceUpDown", Text = "Slice Up/Down"},
                    new SelectListItem {Value = "sliceUpDownLeft", Text = "Slice Up/Down/Left"},
                    new SelectListItem {Value = "fold", Text = "Fold"},
                    new SelectListItem {Value = "fade", Text = "Fade"},
                    new SelectListItem {Value = "slideInRight", Text = "Slide In Right"},
                    new SelectListItem {Value = "slideInLeft", Text = "Slide In Left"},
                    new SelectListItem {Value = "boxRandom", Text = "Box Random"},
                    new SelectListItem {Value = "boxRain", Text = "Box Rain"},
                    new SelectListItem {Value = "boxRainReverse", Text = "Box Rain Reverse"},
                    new SelectListItem {Value = "boxRainGrow", Text = "Box Rain Grow"},
                    new SelectListItem {Value = "boxRainGrowReverse", Text = "Box Rain Grow & Reverse"}
                }, "Value", "Text");
            }
        }
    }
}

StirCrazy.Admin/Controllers/CarouselController.cs
using System.Web;
using System.Web.Mvc;
using StirCrazy.Admin.Models.Carousel;
using StirCrazy.Core.Constants;
using StirCrazy.Core.Domain;
using StirCrazy.Core.Services;

namespace StirCrazy.Admin.Controllers
{
    [Authorize]
    public class CarouselController : Controller
    {
        private readonly IMediaService _mediaService;

        public CarouselController(IMediaService mediaService)
        {
            _mediaService = mediaService;
        }

        public ActionResult Index()
        {
            var model = _mediaService.Get(UploadFolder.Carousel);
            return View(model);
        }

        public ActionResult Create()
        {
            var model = new CarouselModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase carouselImage, CarouselModel model)
        {
            var image = new MediaFile
            {
                Id = model.Id,
                Transition = model.Transition ?? "sliceUpDown",
                IsActive = true
            };

            _mediaService.Save(carouselImage, image, Server.MapPath("~/"), UploadFolder.Carousel);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var carousel = _mediaService.Get(id);
            var model = new CarouselModel
            {
                Id = carousel.Id,
                PhysicalPath = carousel.PhysicalPath,
                Filename = carousel.Filename,
                FilePath = carousel.FilePath,
                Transition = carousel.Transition,
                IsActive = !(carousel.IsActive)
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(CarouselModel model)
        {
            if (ModelState.IsValid)
            {
                var carouselImage = new MediaFile()
                {
                    Id = model.Id,
                    PhysicalPath = model.PhysicalPath,
                    FilePath = model.FilePath,
                    Filename = model.Filename,
                    Transition = model.Transition,
                    IsActive = !(model.IsActive)
                };

                _mediaService.Update(carouselImage);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Remove(int id)
        {
            _mediaService.Remove(id);
            return null;
        }
    }
}

StirCrazy.Admin/Views/Carousel/Create.cshtml
@model StirCrazy.Admin.Models.Carousel.CarouselModel
<div class="col-lg-12">
    <h2><strong>Carousel</strong> manager</h2>
    <br>
    <div class="panel panel-default">
        <div class="panel-heading bg-dark">
            <h3 class="panel-title"><strong>Carousel </strong> manager</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                @using (Html.BeginForm("Create", "Carousel", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <div class="form-group">
                        <input type="file" name="carouselImage" id="carouselImage" class="btn btn-default">
                        @Html.DropDownListFor(model => model.Transition, Model.TransitionsList, "-- Choose Transition --", new { @class = "form-control", style = "width: auto" })
                    </div>
                    <div class="form-group">
                        @Html.CheckBoxFor(model => model.IsActive)
                        <label>Hidden</label>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-save"></i> Save & Finish
                            </button>
                            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

StirCrazy.Admin/Views/Carousel/Edit.cshtml
@model StirCrazy.Admin.Models.Carousel.CarouselModel
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading bg-dark">
            <h3 class="panel-title"><strong>Carousel </strong> manager</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                @using (Html.BeginForm("Create", "Carousel", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(model => model.Id)
                    
                    <div class="form-group">
                        @Html.DropDownListFor(model => model.Transition, Model.TransitionsList, Model.Transition, new { @class = "form-control", style = "width: auto" })
                    </div>
                    <div class="form-group">
                        <label>Hidden</label>
                        @Html.CheckBoxFor(model => model.IsActive)
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-save"></i> Save & Finish
                            </button>
                            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

StirCrazy.Admin/Views/Carousel/Index.cshtml
@model IEnumerable<StirCrazy.Core.Domain.MediaFile>
<div class="col-lg-12">
    <h2><strong>Carousel</strong> manager</h2>
    <br>
    <div class="panel panel-default">
        <div class="panel-heading bg-dark">
            <h3 class="panel-title"><strong>Carousel </strong> images</h3> <a href="/Carousel/Create" class="btn btn-default btn-rounded btn-sm pull-right"><i class="fa fa-plus"></i> Carousel Image</a>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 table-responsive filter-right">
                    @if (!Model.Any())
                    {
                        <div class="alert alert-info">No Carousel Images Found.</div>
                    }
                    else
                    {
                        <table id="datatable" class="table table-striped table-hover table-dynamic table-dark dataTable">
                            <thead>
                                <tr style="text-align: left">
                                    <th>Image</th>
                                    <th>Transition</th>
                                    <th style="width: 10px; text-align: center">Displayed</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody id="carousel">
                                @foreach (var carousel in Model)
                                {
                                    <tr id="@carousel.Id">
                                        <td style="width: 125px">
                                            <img src="@carousel.FilePath" width="140" height="90">
                                        </td>
                                        <td style="width: 150px">
                                            @carousel.Transition
                                        </td>
                                        <td style="width: 10px; text-align: center">
                                            <i class="@((carousel.IsActive) ? "fa fa-check" : "")"></i>
                                        </td>
                                        <td style="width: 200px">
                                            @Html.ActionLink("Edit", "Edit", new { id = carousel.Id })<br />
                                            <a href="#" class="remove-item" data-id="@carousel.Id" data-url="/Carousel/Remove">Remove</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#carousel").sortable({
            stop: function (event, ui) {
                var pages = [];
                $(this).children().each(function (index) {
                    pages.push({
                        'id': $(this).attr('id'),
                        'order': index
                    });
                });

                $.post("/Media/UpdateIndex", { 'jsonRequest': JSON.stringify(pages) }, "json");
            }
        });
    });
</script>