StirCrazy/Controllers/BakeryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Routing;
using PayPal.Api.Payments;
using StirCrazy.Core.Constants;
using StirCrazy.Core.Domain;
using StirCrazy.Core.Domain.Orders;
using StirCrazy.Core.Services;
using StirCrazy.Core.Services.Order;
using StirCrazy.Core.Services.Party;
using StirCrazy.Models.Addons;
using StirCrazy.Models.Gallery;
using StirCrazy.Models.Order;

namespace StirCrazy.Controllers
{
    public class BakeryController : AsyncController
    {
        private readonly IMediaService _mediaService;
        private readonly IPartyAddonService _partyAddonService;
        private readonly IBakeryOrderService _bakeryOrderService;
        private readonly IPayPalService _payPalService;
        private readonly IPromotionCodeService _promotionCodeService;

        public BakeryController(IBakeryOrderService bakeryOrderService, 
            IPartyAddonService partyAddonService, 
            IPayPalService payPalService, 
            IPromotionCodeService promotionCodeService, 
            IMediaService mediaService)
        {
            _partyAddonService = partyAddonService;
            _payPalService = payPalService;
            _promotionCodeService = promotionCodeService;
            _mediaService = mediaService;
            _bakeryOrderService = bakeryOrderService;
        }

        public ActionResult Index()
        {
            var model = new GalleryModel
            {
                GalleryImages = _mediaService.Get(UploadFolder.Cakes)
            };

            return View(model);
        }

        public ActionResult CakePans()
        {
            return View();
        }

        public ActionResult Create()
        {
            var model = new BakeryModel
            {
                Addons = _partyAddonService.GetAddons().OrderBy(y => y.Name).Select(x => new AddonModel()
                {
                    Id = x.Id,
                    AddonType = x.AddonType,
                    Name = x.Name,
                    Price = x.Price
                }).ToList(),
                OrderAddons = new List<BakeryOrderAddonModel>(),
                PaymentTransaction = new PaymentTransaction()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Create(BakeryModel model)
        {
            var bakeryOrder = new BakeryOrder()
            {
                PickUpDate = model.PickUpDate,
                PickUpTime = model.PickUpTime,
                Notes = model.Notes,
                Customer = model.Customer,
                Child = model.Child,
                CakeTheme = model.CakeTheme,
                CakeFlavour = model.CakeFlavour,
                EdibleImage = model.EdibleImage,
                StandardImage = model.StandardImage,
                OrderAddons = new List<BakeryOrderAddon>(),
                PaymentTransaction = new PaymentTransaction()
                {
                    Amount = model.Total,
                    PaymentDate = DateTime.Now
                },
                SubTotal = model.SubTotal,
                Tax = model.Tax,
                Total = model.Total,
                Status = OrderStatus.Created
            };

            if (model.Promotion != null)
            {
                var promoCode = _promotionCodeService.Get(model.Promotion);

                if (promoCode != null && promoCode.AdjustmentType == AdjustmentType.Percentage)
                {
                    bakeryOrder.Discount = (promoCode.Adjustment / 100) * bakeryOrder.Total;
                    bakeryOrder.PromotionCode = promoCode;
                }

                if (promoCode != null && promoCode.AdjustmentType == AdjustmentType.Discount)
                {
                    bakeryOrder.Discount = promoCode.Adjustment;
                    bakeryOrder.PromotionCode = promoCode;
                }
            }

            bakeryOrder.Customer.UserName = model.Customer.Email;
            foreach (var orderAddon in model.OrderAddons)
            {
                if (orderAddon.IsSelected || orderAddon.Quantity > 0)
                {
                    bakeryOrder.OrderAddons.Add(new BakeryOrderAddon()
                    {
                        BakeryOrderId = bakeryOrder.Id,
                        AddonId = orderAddon.Id,
                        Addon = orderAddon.Addon,
                        IsIncluded = orderAddon.IsIncluded,
                        Quantity = orderAddon.Quantity,
                    });
                }
            }

            // BYPASS PAYPAL PAYMENT PROCESSING
            if (model.BypassPaypal)
            {
                bakeryOrder.PaymentTransaction.TransactionType = model.PaymentTransaction.TransactionType;
                bakeryOrder.PaymentTransaction.TransactionNumber = model.PaymentTransaction.TransactionNumber ?? "Not Applicable";
                bakeryOrder.PaymentTransaction.PaymentStatus = "Approved";

                // SAVE DATABASE
                bakeryOrder.CreatedBy = "Administrator";
                bakeryOrder.Status = OrderStatus.Paid;
                var order = await _bakeryOrderService.CreateAsync(bakeryOrder);

                // SEND NOTIFICATION
                try { await _bakeryOrderService.SendOrderNotificationAsync(bakeryOrder); }
                catch (Exception ex) { Elmah.ErrorSignal.FromCurrentContext().Raise(ex); }

                return RedirectToAction("Email", new RouteValueDictionary { { "Id", order.Id } });
            }

            // SAVE DATABASE
            bakeryOrder.CreatedBy = "Customer";
            await _bakeryOrderService.CreateAsync(bakeryOrder);

            // PAYPAL PAYMENT PROCESSING
            var baseUri = Request.Url.Scheme + "://" + Request.Url.Authority + "/Bakery/";
            var returnUrl = baseUri + "Payment/" + bakeryOrder.Id;
            var cancelUrl = baseUri + "Cancelled/" + bakeryOrder.Id;

            return await ProcessPayment(bakeryOrder.Id, (double)bakeryOrder.Total, "Stir Crazy - Bakery Order", returnUrl, cancelUrl);
        }

        public async Task<ActionResult> Details(Guid id)
        {
            var bakeryOrder = await _bakeryOrderService.GetAsync(id);
            if (bakeryOrder == null) return HttpNotFound();

            var model = new BakeryModel()
            {
                Id = bakeryOrder.Id,
                Addons = _partyAddonService.GetAddons().OrderBy(y => y.Name).Select(x => new AddonModel()
                {
                    Id = x.Id,
                    AddonType = x.AddonType,
                    Name = x.Name,
                    Price = x.Price
                }).ToList(),
                OrderAddons = bakeryOrder.OrderAddons.Select(x => new BakeryOrderAddonModel()
                {
                    Id = x.Id,
                    Addon = x.Addon,
                    Quantity = x.Quantity,
                    IsIncluded = x.IsIncluded
                }).ToList(),
                CakeFlavour = bakeryOrder.CakeFlavour,
                CakeTheme = bakeryOrder.CakeTheme,
                StandardImage = bakeryOrder.StandardImage,
                EdibleImage = bakeryOrder.EdibleImage,
                Notes = bakeryOrder.Notes,
                Customer = bakeryOrder.Customer,
                Child = bakeryOrder.Child,
                PaymentTransaction = bakeryOrder.PaymentTransaction,
                PickUpDate = bakeryOrder.PickUpDate,
                PickUpTime = bakeryOrder.PickUpTime,
                SubTotal = bakeryOrder.SubTotal,
                Tax = bakeryOrder.Tax,
                Discount = bakeryOrder.Discount,
                Total = bakeryOrder.Total,
                Status = bakeryOrder.Status,
                Promotion = (bakeryOrder.PromotionCode != null)
                ? string.Format("{0} - {1}", bakeryOrder.PromotionCode.Code, bakeryOrder.PromotionCode.Description) : ""
            };

            return View(model);
        }

        public async Task<ActionResult> Print(Guid id)
        {
            var bakeryOrder = await _bakeryOrderService.GetAsync(id);
            if (bakeryOrder == null) return HttpNotFound();

            var model = new BakeryModel()
            {
                Id = bakeryOrder.Id,
                Addons = _partyAddonService.GetAddons().OrderBy(y => y.Name).Select(x => new AddonModel()
                {
                    Id = x.Id,
                    AddonType = x.AddonType,
                    Name = x.Name,
                    Price = x.Price
                }).ToList(),
                OrderAddons = bakeryOrder.OrderAddons.Select(x => new BakeryOrderAddonModel()
                {
                    Id = x.Id,
                    Addon = x.Addon,
                    Quantity = x.Quantity,
                    IsIncluded = x.IsIncluded
                }).ToList(),
                CakeFlavour = bakeryOrder.CakeFlavour,
                CakeTheme = bakeryOrder.CakeTheme,
                StandardImage = bakeryOrder.StandardImage,
                EdibleImage = bakeryOrder.EdibleImage,
                Notes = bakeryOrder.Notes,
                Customer = bakeryOrder.Customer,
                Child = bakeryOrder.Child,
                PaymentTransaction = bakeryOrder.PaymentTransaction,
                PickUpDate = bakeryOrder.PickUpDate,
                PickUpTime = bakeryOrder.PickUpTime,
                SubTotal = bakeryOrder.SubTotal,
                Tax = bakeryOrder.Tax,
                Discount = bakeryOrder.Discount,
                Total = bakeryOrder.Total,
                Status = bakeryOrder.Status,
                Promotion = (bakeryOrder.PromotionCode != null)
                ? string.Format("{0} - {1}", bakeryOrder.PromotionCode.Code, bakeryOrder.PromotionCode.Description) : ""
            };

            return View(model);
        }

        public ActionResult Save(Guid id)
        {

StirCrazy/Views/Bakery/Details.cshtml
@using Microsoft.Ajax.Utilities
@using StirCrazy.Core.Domain.Party
@using StirCrazy.Core.Utilities
@model StirCrazy.Models.Order.BakeryModel
@{ decimal total = 0.00m; }
<div class="row">
    <div class="glow glow_blue" style="color: #333;">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title"><strong>Order</strong> Overview</h3></div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="controls">
                                    <h1>Bakery Order</h1>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="controls">
                                    <h1>@Model.PickUpDate.Date.ToString("ddd MMM dd, yyyy").ToUpper()</h1>
                                    <strong>Pickup Time: </strong> @Model.PickUpTime.GetDisplayName()<br />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="controls">
                                    @if (Model.Notes != null)
                                    {
                                        <br />@Html.Raw(Model.Notes.Replace(Environment.NewLine, "<br/>"))
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title"><strong>Customer</strong> Information</h3></div>
                <div class="panel-body">
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="controls">
                                <h3>@Model.Customer.FullName</h3>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Address</label>
                            <div class="controls">
                                @Model.Customer.Address<br />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Phone Number</label>
                            <div class="controls">
                                @Model.Customer.PhoneNumber
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Email Address</label>
                            <div class="controls">
                                @Model.Customer.Email
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="controls">
                                <h3>@Model.Child.FullName</h3>
                            </div>
                            <div class="form-group">
                                <label class="form-label">Gender</label>
                                <div class="controls">
                                    @Model.Child.Gender.GetDisplayName()
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="form-label">Age</label>
                                <div class="controls">
                                    @Model.Child.Age
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title"><strong>Payment</strong> Details</h3></div>
                <div class="panel-body">
                    <div class="col-xs-12 col-md-12">
                        <h1 class="payment-total">$@Model.Total.ToString("0.00")</h1>
                    </div>
                    <div class="col-xs-12 col-md-12">
                        <span>Sub-total <strong class="pull-right">$@Model.SubTotal.ToString("0.00")</strong></span><br />
                        <span>GST <strong class="pull-right">$@Model.Tax.ToString("0.00")</strong></span><br />
                        @if (Model.Discount > 0)
                        {
                            <br />
                            <span>Discount <strong class="pull-right">$@Model.SubTotal.ToString("0.00")</strong></span><br />
                            <span>Promotion <strong class="pull-right">$@Model.SubTotal.ToString("0.00")</strong></span><br />
                        }

                        @if (Model.PaymentTransaction != null)
                        {
                            <br />
                            <span>Payment <strong class="pull-right">@Model.PaymentTransaction.TransactionType.GetDisplayName() - @Model.PaymentTransaction.PaymentStatus</strong></span><br />
                            <span>Transaction <strong class="pull-right">@(Model.PaymentTransaction.TransactionNumber ?? "Not Applicable")</strong></span><br />
                            <span>Status <strong class="pull-right">@Model.Status</strong></span><br />
                        }
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2>Thank You For Ordering!</h2>
                    <p>
                        Your order is on it's way to our team and we look forward to seeing you soon,
                        you should get a confirmation email from us shortly.<br />
                        Should you wish to change your order please feel free to email us at partycoordinator@("@")stircrazy.ca.
                    </p>
                    <div id="packages-button" class="col-sm-12">
                        <a href="@Url.Action("Save", "Bakery", new RouteValueDictionary { { "Id", @Model.Id } })" target="_blank">Download PDF</a>
                        <a href="@Url.Action("Print", "Bakery", new RouteValueDictionary { { "Id", @Model.Id } })" target="_blank">Print Confirmation</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title"><strong>Order</strong> Details</h3></div>
                <div class="panel-body">
                    <h4>Cake</h4><hr class="dashed" />
                    @if (!Model.CakeFlavour.IsNullOrWhiteSpace() && !Model.CakeTheme.IsNullOrWhiteSpace())
                    {
                        @Model.CakeFlavour.ToUpper() @(" - ") @Model.CakeTheme.ToUpper()
                        <br /><br />
                        <span class="pull-right">Total: $45.00</span>
                    }
                    else
                    { @("--- None ---")<br /> }
                    <br /><h4>Cupcakes</h4><hr class="dashed" />
                    @if (Model.OrderAddons.All(x => x.Addon.AddonType != AddonType.FlavourCupcake))
                    {
                        @("--- None ---")<br />
                    }
                    else
                    {
                        foreach (var cupcake in Model.OrderAddons.Where(x => x.Addon.AddonType == AddonType.FlavourCupcake))
                        {
                            @cupcake.Quantity @(" Dozen - ") @cupcake.Addon.Name @(" ($") @cupcake.Addon.Price @("/Dozen)")<br />
                        }

                        <br /><strong>@("Colour(s): ")</strong>
                        @Html.Raw(string.Join(", ", Model.OrderAddons.Where(x => x.Addon.AddonType == AddonType.FlavourIcing && !x.IsIncluded).Select(y => y.Addon.Name)))
                        <br /><br />
                        <span class="pull-right">Total: $@Model.OrderAddons.Where(x => x.Addon.AddonType == AddonType.FlavourCupcake).Sum(y => y.Quantity * y.Addon.Price)</span>
                    }
                    <br /><h4>Mini Cupcakes</h4><hr class="dashed" />
                    @if (Model.OrderAddons.All(x => x.Addon.AddonType != AddonType.FlavourMiniCupcake))
                    {
                        @("--- None ---")<br />
                    }
                    else
                    {
                        foreach (var cupcake in Model.OrderAddons.Where(x => x.Addon.AddonType == AddonType.FlavourMiniCupcake))
                        {
                            @cupcake.Quantity @(" Dozen - ") @cupcake.Addon.Name @(" ($") @cupcake.Addon.Price @("/Dozen)")<br />
                        }

                        <br /><strong>@("Colour(s): ")</strong>
                        @Html.Raw(string.Join(", ", Model.OrderAddons.Where(x => x.Addon.AddonType == AddonType.FlavourIcing && x.IsIncluded).Select(y => y.Addon.Name)))
                        <br /><br />
                        <span class="pull-right">Total: $@Model.OrderAddons.Where(x => x.Addon.AddonType == AddonType.FlavourMiniCupcake).Sum(y => y.Quantity * y.Addon.Price)</span>
                    }
                    <br /><h4>Edible Images</h4><hr class="dashed" />
                    @if (!Model.StandardImage.IsNullOrWhiteSpace() || !Model.EdibleImage.IsNullOrWhiteSpace())
                    {
                        @Model.StandardImage.ToUpper() @(" (Standard)") <br />
                        @Model.EdibleImage.ToUpper() @(" (Personalized)") <br />
                        if (Model.StandardImage != null || Model.StandardImage != "") { total += 10m; }
                        if (Model.EdibleImage != null || Model.EdibleImage != "") { total += 15m; }
                        <span class="pull-right">Total: $@total</span>
                    }
                    else
                    { @("--- None ---")<br /> }
                </div>
            </div>
        </div>
    </div>
</div>

StirCrazy/Views/Bakery/Index.cshtml
@model StirCrazy.Models.Gallery.GalleryModel

<div class="row">
    <div class="glow glow_blue  text-center">
        <h1 class="stircrazy text-center">Bakery</h1>
        <h4 class="stircrazy">STIR CRAZY CAKES AND CUPCAKES ARE BAKED FRESH ON SITE</h4>
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h3 class="stircrazy">CAKES PRICING</h3>
                <table class="admission striped-blue table-rounded">
                    <tr>
                        <td>
                            ONE SIZE: 10 x 10" Slab<br />
                            <small>
                                (Serves approximately 15-18)<br />
                                Flavours: Vanilla, Chocolate and Marble
                            </small>
                        </td>
                        <td class="text-right" style="width: 50px">$45.00</td>
                        <td id="packages-button-sm" style="width: 50px"><a href="@Url.Action("Create", "Bakery")">Order</a></td>
                    </tr>
                </table>
                <br />
                <p>Cakes And Cupcakes Are Available For Purchase<br />For On And Off-Site Celebrations!<br /><small>Available In Gluten Free!</small></p>
            </div>
            <div class="col-sm-12 col-md-6">
                <h3 class="stircrazy">CUPCAKES SIZES & PRICING</h3>
                <table class="admission striped-blue table-rounded">
                    <tr>
                        <td>
                            Standard Dozen
                        </td>
                        <td class="text-right" style="width: 50px">$20.00</td>
                        <td id="packages-button-sm" style="width: 50px"><a href="@Url.Action("Create", "Bakery")">Order</a></td>
                    </tr>
                    <tr>
                        <td>
                            Mini Dozen
                        </td>
                        <td class="text-right" style="width: 50px">$7.00</td>
                        <td id="packages-button-sm" style="width: 50px"><a href="@Url.Action("Create", "Bakery")">Order</a></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h3 class="stircrazy">EDIBLE CAKE IMAGE PRICING</h3>
                <table class="admission striped-blue table-rounded">
                    <tr>
                        <td>
                            Standard Edible Images
                        </td>
                        <td class="text-right" style="width: 50px">$10.00</td>
                        <td id="packages-button-sm" style="width: 50px"><a href="@Url.Action("Create", "Bakery")">Order</a></td>
                    </tr>
                    <tr>
                        <td>
                            Photo Edible Images
                        </td>
                        <td class="text-right" style="width: 50px">$15.00</td>
                        <td id="packages-button-sm" style="width: 50px"><a href="@Url.Action("Create", "Bakery")">Order</a></td>
                    </tr>
                </table>
                <p>
                    CUSTOM IMAGING SUCH AS COMPANY LOGOS AVAILABLE!
                    TO CUSTOMIZE YOUR BAKERY ORDER EMAIL TO
                    <a href="mailto:bakery@stircrazy.ca">BAKERY@("@")STIRCRAZY.CA</a>
                </p>
            </div>
            <div class="col-sm-12 col-md-6">
            </div>
        </div>
    </div>
</div>