StirCrazy.Admin/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using StirCrazy.Admin.Models.Dashboard;
using StirCrazy.Admin.Models.Reporting;
using StirCrazy.Core.Constants;
using StirCrazy.Core.Domain.Orders;
using StirCrazy.Core.Domain.Reports;
using StirCrazy.Core.Services;
using StirCrazy.Core.Utilities;

namespace StirCrazy.Admin.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private readonly IReportingService _reportingService;

        public ReportsController(IReportingService reportingService)
        {
            _reportingService = reportingService;
        }

        public ActionResult Generate()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Generate(ReportModel model)
        {
            if (model.ReportType == ReportType.BakeryReport)
            {
                var bakeryOrders = _reportingService.GetBakeryOrders(model.StartDate, model.EndDate).ToList();
                var partyOrders = _reportingService.GetPartyOrders(model.StartDate, model.EndDate).ToList();

                return View("Print", new BakeryReportModel
                {
                    BakeryOrders = bakeryOrders,
                    PartyOrders = partyOrders
                });
            }

            return View();
        }

        public ActionResult Index()
        {
            var model = new OverviewModel()
            {
                BakeryOrders = _reportingService.GetBakeryOrders(DateTime.Now, null),
                PartyOrders = _reportingService.GetPartyOrders(DateTime.Now, null),
                GrabNGoOrders = _reportingService.GetGrabNGoOrders(DateTime.Now, null),
                RoomRentals = _reportingService.GetRoomOrders(DateTime.Now, null),
                CorporateEvents = _reportingService.GetCorporateEvents(DateTime.Now, null),
                AnnualPassOrders = _reportingService.GetAnnualPassOrders(DateTime.Now, null)
            };

            var list = new List<OrderViewModel>();

            list.AddRange(model.BakeryOrders.Select(x => new OrderViewModel()
            {
                Id = x.Id.ToString(),
                Type = OrderType.Bakery,
                Customer = x.Customer,
                ScheduledDate = (x.PickUpDate.ToString("MMM dd, yyyy") + " " + x.PickUpTime.GetDisplayName()),
                Transaction = x.PaymentTransaction,
                Status = x.Status,
                Total = x.Total
            }));
            
            list.AddRange(model.AnnualPassOrders.Select(x => new OrderViewModel()
            {
                Id = x.Id.ToString(),
                Type = OrderType.AnnualPass,
                Customer = x.Parent,
                ScheduledDate = (x.PickUpDate.ToString("MMM dd, yyyy") + " " + x.PickUpTime.GetDisplayName()),
                Transaction = x.PaymentTransaction,
                Status = x.Status,
                Total = x.Total
            }));

            list.AddRange(model.GrabNGoOrders.Select(x => new OrderViewModel()
            {
                Id = x.Id.ToString(),
                Type = OrderType.GrabNGo,
                Customer = x.Customer,
                ScheduledDate = x.PickUpDate.ToString("MMM dd, yyyy") + " " + x.PickUpTime.GetDisplayName(),
                Transaction = x.PaymentTransaction,
                Status = x.Status,

                Total = x.Total
            }));

            list.AddRange(model.RoomRentals.Select(x => new OrderViewModel()
            {
                Id = x.Id.ToString(),
                Customer = x.Customer,
                ScheduledDate = (x.RoomBooking.Date.ToString("MMM dd, yyyy") + "<br />"
                            + x.RoomBooking.TimeSlot.StartTime.ToString("h:mm tt")
                            + " - " + x.RoomBooking.TimeSlot.EndTime.ToString("h:mm tt")),
                Transaction = x.PaymentTransaction,
                Booking = x.RoomBooking,
                Status = x.Status,
                Type = OrderType.Room,
                Total = x.Total
            }));

            list.AddRange(model.CorporateEvents.Select(x => new OrderViewModel()
            {
                Id = x.Id.ToString(),
                Customer = x.Customer,
                ScheduledDate = (x.Date.ToString("MMM dd, yyyy") + "<br />"
                            + x.StartTime.ToString()
                            + " - " + x.EndTime.ToString()),
                Status = x.Status,
                Type = OrderType.Room,
                Total = 0.00m
            }));

            list.AddRange(model.PartyOrders.Select(x => new OrderViewModel()
            {
                Id = x.Id.ToString(),
                Customer = x.Parent,
                ScheduledDate = (x.RoomBooking.Date.ToString("MMM dd, yyyy") + "<br />"
                            + x.RoomBooking.TimeSlot.StartTime.ToString("h:mm tt")
                            + " - " + x.RoomBooking.TimeSlot.EndTime.ToString("h:mm tt")),
                Transaction = x.PaymentTransaction,
                Booking = x.RoomBooking,
                Package = x.PartyPackage,
                Status = x.Status,
                Type = OrderType.Party,
                Total = x.Total,
                cssClass = GetCssClass((x.RoomBooking != null) ? x.RoomBooking.PartyRoomId : 0)
            }));

            list = new List<OrderViewModel>(list.OrderBy(x => x.OrderDate));
            return View(list);
        }

        public ActionResult Monthly(int id = 0)
        {
            var month = id;
            if (month == 0) month = DateTime.Now.Month;
            var year = DateTime.Now.Year;

            var firstDay = new DateTime(year, month, 1);
            var lastDay = new DateTime(year, month, 1).AddMonths(1).AddDays(-1);

            var bakeryOrders = _reportingService.GetBakeryOrders(firstDay, lastDay);
            var partyOrders = _reportingService.GetPartyOrders(firstDay, lastDay);
            var grabNGoOrders = _reportingService.GetGrabNGoOrders(firstDay, lastDay);
            var roomRentals = _reportingService.GetRoomOrders(firstDay, lastDay);
            var corporateEvents = _reportingService.GetCorporateEvents(firstDay, lastDay);
            var annualPasses = _reportingService.GetAnnualPassOrders(firstDay, lastDay);

            var reports = new List<MonthReportModel>
            {
                new MonthReportModel()
                {
                    Month = month,
                    Type = OrderType.AnnualPass,
                    Orders = annualPasses.Count(),
                    Total = annualPasses.Sum(x => x.Total)
                },
                new MonthReportModel()
                {
                    Month = month,
                    Type = OrderType.Bakery,
                    Orders = bakeryOrders.Count(),
                    Total = bakeryOrders.Sum(x => x.Total)
                },
                new MonthReportModel()
                {
                    Month = month,
                    Type = OrderType.Party,
                    Orders = partyOrders.Count(),
                    Total = partyOrders.Sum(x => x.Total)
                },
                new MonthReportModel()
                {
                    Month = month,
                    Type = OrderType.GrabNGo,
                    Orders = grabNGoOrders.Count(),
                    Total = grabNGoOrders.Sum(x => x.Total)
                },
                new MonthReportModel()
                {
                    Month = month,
                    Type = OrderType.Room,
                    Orders = roomRentals.Count(),
                    Total = roomRentals.Sum(x => x.Total)
                },
                new MonthReportModel()
                {
                    Month = month,
                    Type = OrderType.CorporateEvent,
                    Orders = corporateEvents.Count(),
                    Total = corporateEvents.Sum(x => x.Total)
                }
            };

            var model = new MonthOverviewModel
            {
                MonthReports = reports, 
                Month = (Month) month
            };

            return View(model);
        }

        public ActionResult Packages(int id = 0)
        {
            var month = id;
            if (month == 0) month = DateTime.Now.Month;
            var year = DateTime.Now.Year;

            var firstDay = new DateTime(year, month, 1);
            var lastDay = new DateTime(year, month, 1).AddMonths(1).AddDays(-1);

            var partyOrders = _reportingService.GetPartyOrders(firstDay, lastDay);

            var model = new PackagesReportModel()
            {
                Month = (Month)month,
                Packages = partyOrders.Select(x => x.PartyPackage).ToList()
            };

            return View(model);
        }

        private string GetCssClass(int roomId)
        {
            switch (roomId)
            {
                case 1:
                    return "rocknroll-red";

                case 2:
                    return "mellow-yellow";

                case 3:
                    return "bebop-blue";

                case 4:
                    return "outrageous-orange";

                case 5:
                    return "sublime-lime";

                case 6:
                    return "playful-purple";
            }

            return null;
        }
    }
}

StirCrazy.Admin/Views/Reports/Generate.cshtml
@model StirCrazy.Admin.Models.Reporting.ReportModel
@Styles.Render("~/Content/datetimepicker")
@Scripts.Render("~/bundles/datetimepicker")

<div class="col-lg-12">
    @using (Html.BeginForm("Generate", "Reports", FormMethod.Post, new { @id = "Availability" }))
    {
        <!-- DATE/TIME -->
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><h3 class="panel-title"><strong>Store</strong> Reports</h3></div>
                    <div class="panel-body">
                        <div class="col-md-12">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label><i class="fa fa-calendar"></i>  Choose A Date Range</label><br />
                                    <div class="col-sm-2">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row" id="DatePair">
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>From</label>
                                    @Html.TextBoxFor(model => model.StartDate, new { @class = "form-control date start" })
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>Until</label>
                                    @Html.TextBoxFor(model => model.EndDate, new { @class = "form-control date end" })
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>Until</label>
                                    @Html.EnumDropDownListFor(model => model.ReportType, "-- Choose Report --", new { @style = "width: auto" })
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>Until</label>
                                    <input type="submit" name="submit" value="Run Report" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<link href="~/Scripts/plugins/jquery.timepicker/jquery.timepicker.css" type="text/css" rel="stylesheet" />
<script type="text/javascript" src="~/Scripts/plugins/jquery.timepicker/jquery.timepicker.min.js"></script>
<script type="text/javascript" src="~/Scripts/plugins/jquery.datepair/Datepair.js"></script>
<script type="text/javascript" src="~/Scripts/plugins/jquery.datepair/jquery.datepair.js"></script>
<script>

    $('#DatePair .date').datetimepicker({
        format: 'm/d/Y',
        autoclose: true,
        timepicker: false
    });

    $('#DatePair').datepair();
</script>

StirCrazy.Admin/Views/Reports/Index.cshtml
@using StirCrazy.Core.Domain.Orders
@using StirCrazy.Core.Utilities
@model List<StirCrazy.Admin.Models.Dashboard.OrderViewModel>

<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading bg-dark">
            <h3 class="panel-title"><strong>Order </strong> Overview</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 table-responsive filter-right">
                    @if (!Model.Any())
                    {
                        <div class="alert bg-gray-light">
                            It doesn't look like you have any orders currently.
                        </div>
                    }
                    else
                    {
                        <table id="datatable" class="table table-striped table-hover table-dynamic table-dark dataTable">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Type</th>
                                    <th>Scheduled</th>
                                    <th>Room</th>
                                    <th>Description</th>
                                    <th>Name</th>
                                    <th>Address</th>
                                    <th>Phone</th>
                                    <th>Email</th>
                                    <th>Total</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td style="width: 1px" class="@item.cssClass"></td>
                                        <td>
                                            @item.Type.GetDisplayName()
                                        </td>
                                        <td>
                                            @Html.Raw(item.OrderDate)
                                        </td>
                                        <td style="width: 2px">
                                            @if (item.Booking != null)
                                            {
                                                @item.Booking.PartyRoom.Name @(" ")
                                            }
                                            @if (item.Type == OrderType.CorporateEvent)
                                            {
                                                @("- Facility -")
                                            }
                                        </td>
                                        <td>
                                            @if (item.Package != null)
                                            {
                                                @item.Package.Name
                                            }
                                        </td>
                                        <td>
                                            @(!string.IsNullOrEmpty(item.Customer.FullName) ? item.Customer.FullName : item.Customer.BusinessName)
                                        </td>
                                        <td>
                                            @item.Customer.Address<br />
                                            @item.Customer.City,
                                            @item.Customer.Province
                                        </td>
                                        <td>
                                            @item.Customer.PhoneNumber
                                        </td>
                                        <td>
                                            @item.Customer.Email
                                        </td>

                                        <td>
                                            @item.Total
                                        </td>
                                        <td>
                                            @item.Status
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

StirCrazy.Admin/Views/Reports/Monthly.cshtml
@using System.Globalization
@using StirCrazy.Core.Utilities
@model StirCrazy.Admin.Models.Reporting.MonthOverviewModel

<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading"><h1 class="panel-title"><strong>Monthly</strong> Report</h1></div>
        <div class="panel-body">
            <div class="col-md-6">
                @Html.EnumDropDownListFor(model => model.Month, new { id = "Month", @class = "form-control", style = "width: auto" })
            </div>
            <div class="col-md-6">
                <h3 class="pull-right">@CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName((int)Model.Month)<br />
                <strong>@string.Format("{0:C}", Model.MonthReports.Sum(x => x.Total))</strong></h3>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading"><h1 class="panel-title"><strong>@CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName((int)Model.Month)</strong> Overview</h1></div>
        <div class="panel-body">

            @foreach (var item in Model.MonthReports)
            {
                <div class="col-lg-3 col-md-6">
                    <div class="panel no-bd bd-3 panel-stat">
                        <div class="panel-body bg-blue">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="stat-num">
                                        <h1 class="m-0 w-300">@item.Orders</h1>
                                    </div>
                                    <h3>@item.Type.GetDisplayName()</h3>
                                    <h2 class="text=center">@string.Format("{0:C}", item.Total)</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>
<script>
    $(document).on('change', '#Month', function () {
        window.location.href = "/reports/monthly/" + $('#Month').val();
    });
</script>

StirCrazy.Admin/Views/Reports/Packages.cshtml
@using System.Globalization
@model StirCrazy.Admin.Models.Reporting.PackagesReportModel

<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading"><h1 class="panel-title"><strong>Monthly</strong> Report</h1></div>
        <div class="panel-body">
            <div class="col-md-6">
                @Html.EnumDropDownListFor(model => model.Month, new { id = "Month", @class = "form-control", style = "width: auto" })
            </div>
            <div class="col-md-6">
                <h3 class="pull-right">
                    @CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName((int)Model.Month)<br />
            </h3>
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><h1 class="panel-title"><strong>@CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName((int)Model.Month)</strong> Overview</h1></div>
    <div class="panel-body">
        <div class="col-lg-3 col-md-6">
            <div class="panel no-bd bd-3 panel-stat">
                <div class="panel-body bg-blue">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="stat-num">
                                <h2 class="m-0 w-300">Package #1</h2>
                            </div>
                            <h2 class="text=center">@Model.Packages.Count(x => x.Id == 1) SOLD</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel no-bd bd-3 panel-stat">
                <div class="panel-body bg-blue">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="stat-num">
                                <h2 class="m-0 w-300">Package #2</h2>
                            </div>
                            <h2 class="text=center">@Model.Packages.Count(x => x.Id == 2) SOLD</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel no-bd bd-3 panel-stat">
                <div class="panel-body bg-blue">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="stat-num">
                                <h2 class="m-0 w-300">Package #3</h2>
                            </div>
                            <h2 class="text=center">@Model.Packages.Count(x => x.Id == 3) SOLD</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel no-bd bd-3 panel-stat">
                <div class="panel-body bg-blue">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="stat-num">
                                <h2 class="m-0 w-300">Build Your Own</h2>
                            </div>
                            <h2 class="text=center">@Model.Packages.Count(x => x.Id == 4) SOLD</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<script>
    $(document).on('change', '#Month', function () {
        window.location.href = "/reports/packages/" + $('#Month').val();
    });
</script>

StirCrazy.Admin/Views/Reports/Print.cshtml
@using StirCrazy.Core.Domain.Party
@using StirCrazy.Core.Utilities
@model StirCrazy.Admin.Models.Reporting.BakeryReportModel
@{ Layout = null; }
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <style type="text/css">
        body {
            font: 9pt/1.2 Arial, sans-serif;
        }

        .content {
            width: 9.5in;
        }

        .floating-div {
            float: left;
            margin: 1%;
        }

        .floating-div-left {
            width: 55%;
        }

        .floating-div-right {
            width: 40%;
        }

        .row {
            margin-left: 0;
            margin-right: 0;
        }
    </style>
</head>
<body>
    <div class="content">
        <img src="/img/logo.png" />
        <br>
        <div class="floating-div floating-div-left">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title"><strong>Bakery</strong> Cakes</h3></div>
                <div class="panel-body">
                    <div class="row">

                        @foreach (var bakeryOrders in Model.BakeryOrders.GroupBy(x => x.PickUpDate.Date))
                        {
                            <h2>@bakeryOrders.Key.Date.ToString("dddd MMM d")</h2>
                            if (bakeryOrders.All(x => string.IsNullOrEmpty(x.CakeFlavour) || string.IsNullOrEmpty(x.CakeTheme)))
                            {
                                <strong>None</strong><br />
                            }
                            else
                            {
                                foreach (var bakeryOrder in bakeryOrders)
                                {
                                    if (!string.IsNullOrEmpty(bakeryOrder.CakeFlavour) || !string.IsNullOrEmpty(bakeryOrder.CakeTheme))
                                    {
                                        @bakeryOrder.CakeFlavour @(" - ") @bakeryOrder.CakeTheme <br />
                                    }
                                }
                            }
                        }
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title"><strong>Party</strong> Cakes</h3></div>
                <div class="panel-body">
                    <div class="row">
                        @foreach (var partyOrders in Model.PartyOrders.GroupBy(x => x.RoomBooking.Date.Date))
                        {
                            <h2>@partyOrders.Key.Date.ToString("dddd MMM d")</h2>
                            if (partyOrders.All(x => string.IsNullOrEmpty(x.CakeFlavour) || string.IsNullOrEmpty(x.CakeTheme)))
                            {
                                <strong>None</strong><br />
                            }
                            else
                            {
                                foreach (var partyOrder in partyOrders)
                                {
                                    if (!string.IsNullOrEmpty(partyOrder.CakeFlavour) || !string.IsNullOrEmpty(partyOrder.CakeTheme))
                                    {
                                        @partyOrder.CakeFlavour @(" - ") @partyOrder.CakeTheme <br />
                                    }
                                }
                            }
                        }
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading"><h3 class="panel-title"><strong>Cupcake</strong> Orders</h3></div>
                    <div class="panel-body">
                        <div class="row">
                            @{
                                foreach (var partyOrders in Model.PartyOrders.GroupBy(x => x.RoomBooking.Date.Date))
                                {
                                    var result = partyOrders
                                         .SelectMany(x => x.PartyAddons.Where(o => o.Addon.AddonType == AddonType.FlavourMiniCupcake || o.Addon.AddonType == AddonType.FlavourCupcake || o.Addon.AddonType == AddonType.FlavourIcing))
                                         .GroupBy(addon => new { addon.Addon.AddonType, addon.Addon.Name })
                                         .Select(grouping => new
                                         {
                                             Name = grouping.Key.Name,
                                             Type = grouping.Key.AddonType,
                                             Quantity = grouping.Sum(addon => addon.Quantity),
                                             Flavours = grouping.Where(x => x.Addon.AddonType == AddonType.FlavourIcing)
                                         });

                                    <h2>@partyOrders.Key.Date.ToString("dddd MMM d")</h2>
                                    foreach (var cupcakes in result)
                                    {
                                            <strong>@cupcakes.Quantity@("x ")</strong>
                                            @cupcakes.Name
                                            foreach (var flavour in cupcakes.Flavours)
                                            {
                                                @flavour.Addon.Name @(" ")
                                            }
                                            <br />
                                    }
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="floating-div floating-div-right">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title"><strong>Food</strong> Orders</h3></div>
                <div class="panel-body">
                    <div class="row">
                        @{
                            foreach (var partyOrder in Model.PartyOrders.GroupBy(x => x.RoomBooking.Date.Date))
                            {
                                var result = partyOrder
                                    .SelectMany(x => x.PartyAddons)
                                    .GroupBy(addon => new { addon.Addon.AddonType, addon.Addon.Name })
                                    .Select(grouping => new
                                    {
                                        Name = grouping.Key.Name,
                                        Type = grouping.Key.AddonType,
                                        Quantity = grouping.Sum(addon => addon.Quantity)
                                    });

                                <h2>@partyOrder.Key.Date.ToString("dddd MMM d")</h2>
                                foreach (var addons in result.Where(x => x.Type == AddonType.FoodPlatter || x.Type == AddonType.FoodPizza).GroupBy(x => x.Type))
                                {
                                    <h4>@addons.Key.GetDisplayName()</h4>
                                    foreach (var addon in addons)
                                    {
                                        <strong>@addon.Quantity@("x ")</strong> @addon.Name <br />
                                    }
                                }
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="clear:both"></div>
</body>
</html>