StirCrazy.Admin/Controllers/CorporateEventsController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using StirCrazy.Admin.Models.Party;
using StirCrazy.Core.Domain;
using StirCrazy.Core.Domain.Orders;
using StirCrazy.Core.Services;

namespace StirCrazy.Admin.Controllers
{
    [Authorize]
    public class CorporateEventsController : AsyncController
    {
        private readonly ICorporateEventService _corporateEventService;
        private readonly IRoomBookingService _roomBookingService;

        public CorporateEventsController(ICorporateEventService corporateEventService, IRoomBookingService roomBookingService)
        {
            _corporateEventService = corporateEventService;
            _roomBookingService = roomBookingService;
        }

        public ActionResult Index(OrderStatus status = OrderStatus.Created)
        {
            var model = _corporateEventService.GetByStatus(status).Select(x => new CorporateEventModel()
            {
                Id = x.Id,
                Date = x.Date,
                Customer = x.Customer,
                StartTime = x.StartTime.ToString(),
                EndTime = x.EndTime.ToString(),
                CreatedBy = x.CreatedBy,
                IsAllDay = x.IsAllDay,
                Status = x.Status
            });
            return View(model);
        }

        [HttpPost]
        public JsonResult Availability(DateTime searchDate, string startTime, string endTime)
        {
            DateTime openTime = DateTime.Now;
            DateTime closeTime = DateTime.Now;

            if (startTime != null && endTime != null)
            {
                openTime = DateTime.ParseExact(startTime, "h:mm tt", CultureInfo.InvariantCulture);
                closeTime = DateTime.ParseExact(endTime, "h:mm tt", CultureInfo.InvariantCulture);
            }

            var bookings = _roomBookingService.CheckAvailability(searchDate, openTime.TimeOfDay, closeTime.TimeOfDay);

            return Json(bookings, JsonRequestBehavior.DenyGet);
        }


        public ActionResult Create()
        {
            var model = new CorporateEventModel()
            {
                Date = DateTime.Now
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(CorporateEventModel model)
        {
            if (ModelState.IsValid)
            {
                DateTime startTime = new DateTime();
                DateTime endTime = new DateTime();

                if (model.StartTime != null && model.EndTime != null)
                {
                    startTime = DateTime.ParseExact(model.StartTime, "h:mm tt", CultureInfo.InvariantCulture);
                    endTime = DateTime.ParseExact(model.EndTime, "h:mm tt", CultureInfo.InvariantCulture);
                }

                var corporateEvent = new CorporateEvent()
                {
                    Date = model.Date,
                    Customer = model.Customer,
                    StartTime = startTime.TimeOfDay,
                    EndTime = endTime.TimeOfDay,
                    IsAllDay = model.IsAllDay,
                    Notes = model.Notes,
                    CreatedBy = User.Identity.Name,
                    Total = model.Total,
                    Status = OrderStatus.Scheduled
                };

                _corporateEventService.Add(corporateEvent);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Details(Guid id)
        {
            var corporateEvent = _corporateEventService.Get(id);
            if (corporateEvent == null) return HttpNotFound();

            var model = new CorporateEventModel()
            {
                Id = corporateEvent.Id,
                IsAllDay = corporateEvent.IsAllDay,
                Date = corporateEvent.Date,
                StartTime = corporateEvent.StartTime.ToString(),
                EndTime = corporateEvent.EndTime.ToString(),
                Customer = corporateEvent.Customer,
                CreatedBy = corporateEvent.CreatedBy,
                CustomerId = corporateEvent.CustomerId,
                Notes = corporateEvent.Notes,
                Status = corporateEvent.Status
            };

            return View(model);
        }

        public ActionResult Print(Guid id)
        {
            var corporateEvent = _corporateEventService.Get(id);
            if (corporateEvent == null) return HttpNotFound();

            var model = new CorporateEventModel()
            {
                Id = corporateEvent.Id,
                IsAllDay = corporateEvent.IsAllDay,
                Date = corporateEvent.Date,
                StartTime = corporateEvent.StartTime.ToString(),
                EndTime = corporateEvent.EndTime.ToString(),
                Customer = corporateEvent.Customer,
                CreatedBy = corporateEvent.CreatedBy,
                CustomerId = corporateEvent.CustomerId,
                Notes = corporateEvent.Notes,
                Status = corporateEvent.Status
            };

            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Save(Guid id)
        {
            string baseUri = Request.Url.Scheme + "://" + Request.Url.Authority + "/CorporateEvents/";
            string detailsUrl = baseUri + "Print/" + id;

            byte[] bytesAsPdf = _corporateEventService.GetPdfBytes(detailsUrl);
            if (bytesAsPdf.Any())
                return File(bytesAsPdf, "application/pdf", "Event_Confirmation.pdf");

            return HttpNotFound();
        }

        [AllowAnonymous]
        public ActionResult Email(Guid id)
        {
            var partyOrder = _corporateEventService.Get(id);
            if (partyOrder == null) return HttpNotFound();

            string baseUri = Request.Url.Scheme + "://" + Request.Url.Authority + "/CorporateEvents/";
            _corporateEventService.SendEmail(baseUri, partyOrder.Id, partyOrder.Customer.Email); ;

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Delete(Guid id)
        {
            var corporateEvent = _corporateEventService.Get(id);
            if (corporateEvent == null) return HttpNotFound();

            var model = new CorporateEventModel()
            {
                Id = corporateEvent.Id,
                IsAllDay = corporateEvent.IsAllDay,
                Date = corporateEvent.Date,
                StartTime = corporateEvent.StartTime.ToString(),
                EndTime = corporateEvent.EndTime.ToString(),
                Customer = corporateEvent.Customer,
                CreatedBy = corporateEvent.CreatedBy,
                CustomerId = corporateEvent.CustomerId,
                Notes = corporateEvent.Notes,
                Status = corporateEvent.Status
            };

            return View(model);
        }

        [HttpPost]
        public async Task<RedirectToRouteResult> Delete(CorporateEventModel model)
        {
            await _corporateEventService.CancelAsync(model.Id);
            return RedirectToAction("Index");
        }

        public async Task<RedirectToRouteResult> Cancelled(Guid id)
        {
            await _corporateEventService.CancelAsync(id);
            return RedirectToAction("Index", "Home");
        }
    }
}

StirCrazy.Admin/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Routing;
using PayPal.Api.Payments;
using StirCrazy.Admin.Models.Order;
using StirCrazy.Admin.Models.Party;
using StirCrazy.Core.Domain;
using StirCrazy.Core.Domain.Orders;
using StirCrazy.Core.Services;
using StirCrazy.Core.Services.Order;

namespace StirCrazy.Admin.Controllers
{
    [Authorize]
    public class RoomController : AsyncController
    {
        private readonly IRoomBookingService _roomBookingService;
        private readonly IRoomOrderService _roomOrderService;
        private readonly IPayPalService _payPalService;

        public RoomController(IRoomBookingService roomBookingService,
            IRoomOrderService roomOrderService,
            IPayPalService payPalService)
        {
            _roomBookingService = roomBookingService;
            _roomOrderService = roomOrderService;
            _payPalService = payPalService;
        }

        public ActionResult Index(OrderStatus status = OrderStatus.Created)
        {
            var model = _roomOrderService.GetByStatus(status).Select(x => new RoomOrderModel()
            {
                Id = x.Id,
                RoomBookingId = x.RoomBookingId,
                PayPalTransactionId = x.PaymentTransactionId,
                Notes = x.Notes,
                Total = x.Total,
                DateCreated = x.DateCreated,
                CreatedBy = x.CreatedBy,
                Status = x.Status,
                Customer = x.Customer,
                RoomBooking = new RoomBookingModel()
                {
                    Id = x.RoomBooking.Id,
                    Date = x.RoomBooking.Date,
                    PartyRoom = x.RoomBooking.PartyRoom,
                    PartyRoomId = x.RoomBooking.PartyRoomId,
                    TimeSlot = x.RoomBooking.TimeSlot,
                    TimeSlotId = x.RoomBooking.TimeSlotId
                },
                PaymentTransaction = x.PaymentTransaction

            }).ToList();

            return View(model);
        }

        public ActionResult Availability(DateTime searchDate)
        {
            var result = _roomBookingService.GetAvailability(searchDate);
            return (!result.Any()) ? null : PartialView("_AvailabilityPartial", result);
        }


        public ActionResult Create()
        {
            var model = new RoomOrderModel();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Create(RoomOrderModel model)
        {
            if (ModelState.IsValid)
            {
                model.Customer.UserName = model.Customer.Email;

                var roomOrder = new RoomOrder()
                {
                    Customer = model.Customer,
                    RoomBooking = new RoomBooking()
                    {
                        BookingType = BookingType.RoomRental,
                        PartyRoomId = model.RoomBooking.PartyRoomId,
                        TimeSlotId = model.RoomBooking.TimeSlotId,
                        Date = model.RoomBooking.Date,
                        Status = Status.Scheduled
                    },
                    Promotion = (model.Promotion ?? "NONE"),
                    PaymentTransaction = new PaymentTransaction()
                    {
                        Amount = model.Total,
                        PaymentDate = DateTime.Now
                    },
                    Notes = model.Notes,
                    SubTotal = model.SubTotal,
                    Tax = model.Tax,
                    Total = model.Total,
                    Status = OrderStatus.Paid
                };

                roomOrder.PaymentTransaction.TransactionType = model.PaymentTransaction.TransactionType;
                roomOrder.PaymentTransaction.TransactionNumber = model.PaymentTransaction.TransactionNumber ?? "Not Applicable";
                roomOrder.PaymentTransaction.PaymentStatus = "Approved";

                // SAVE DATABASE
                roomOrder.CreatedBy = "Administrator";
                var order = await _roomOrderService.CreateAsync(roomOrder);

                return RedirectToAction("Email", new RouteValueDictionary { { "Id", order.Id } });
            }

            return View(model);
        }

        public async Task<ActionResult> Details(Guid id)
        {
            var roomOrder = await _roomOrderService.GetAsync(id);

            if (roomOrder != null)
            {
                var model = new RoomOrderModel()
                {
                    Id = roomOrder.Id,
                    Customer = roomOrder.Customer,
                    RoomBooking = new RoomBookingModel()
                    {
                        PartyRoom = roomOrder.RoomBooking.PartyRoom,
                        TimeSlot = roomOrder.RoomBooking.TimeSlot,
                        Date = roomOrder.RoomBooking.Date
                    },
                    PaymentTransaction = roomOrder.PaymentTransaction,
                    Notes = roomOrder.Notes,
                    SubTotal = roomOrder.SubTotal,
                    Discount = roomOrder.Discount,
                    Tax = roomOrder.Tax,
                    Total = roomOrder.Total,
                    Status = roomOrder.Status,
                    Promotion = (roomOrder.PromotionCode != null)
                ? string.Format("{0} - {1}", roomOrder.PromotionCode.Code, roomOrder.PromotionCode.Description) : "Not Applicable"
                };

                return View(model);
            }

            return HttpNotFound();
        }

        [AllowAnonymous]
        public async Task<ActionResult> Print(Guid id)
        {
            var roomOrder = await _roomOrderService.GetAsync(id);

            if (roomOrder != null)
            {
                var model = new RoomOrderModel()
                {
                    Id = roomOrder.Id,
                    Customer = roomOrder.Customer,
                    RoomBooking = new RoomBookingModel()
                    {
                        PartyRoom = roomOrder.RoomBooking.PartyRoom,
                        TimeSlot = roomOrder.RoomBooking.TimeSlot,
                        Date = roomOrder.RoomBooking.Date
                    },
                    Notes = roomOrder.Notes,
                    PaymentTransaction = roomOrder.PaymentTransaction,
                    Promotion = (roomOrder.PromotionCode != null) ? roomOrder.PromotionCode.Code : "Not Applicable",
                    Total = roomOrder.Total,
                    Status = roomOrder.Status
                };

                return View(model);
            }

            return HttpNotFound();
        }

        [AllowAnonymous]
        public ActionResult Save(Guid id)
        {
            string baseUri = Request.Url.Scheme + "://" + Request.Url.Authority + "/Room/";
            string detailsUrl = baseUri + "Print/" + id;

            byte[] bytesAsPdf = _roomOrderService.GetPdfBytes(detailsUrl);
            if (bytesAsPdf.Any())
                return File(bytesAsPdf, "application/pdf", "Order_Confirmation.pdf");

            return HttpNotFound();
        }

        [AllowAnonymous]
        public async Task<ActionResult> Email(Guid id)
        {
            var roomOrder = await _roomOrderService.GetAsync(id);
            if (roomOrder == null) return HttpNotFound();

            var baseUri = Request.Url.Scheme + "://" + Request.Url.Authority + "/Room/";
            await _roomOrderService.SendEmailAsync(baseUri, roomOrder.Id, roomOrder.Customer.Email); ;

            return RedirectToAction("Details", new RouteValueDictionary { { "Id", id } });
        }

        public async Task<ActionResult> Payment(Guid id)
        {
            var payer = Request["PayerID"];
            var roomOrder = await _roomOrderService.GetAsync(id);

            var payment = new Payment
            {
                id = roomOrder.PaymentTransaction.TransactionNumber,
                state = roomOrder.PaymentTransaction.PaymentStatus
            };

            var result = _payPalService.ExecutePayment(payment, payer);
            if (result.state == "approved")
            {
                roomOrder.Status = OrderStatus.Paid;
            }

            roomOrder.PaymentTransaction.PaymentStatus = result.state;
            await _roomOrderService.UpdateAsync(roomOrder);

            return RedirectToAction("Details", new RouteValueDictionary { { "Id", id } });
        }

        private string GetApprovalUrl(Payment payment)
        {
            List<Links> links = payment.links;
            return (from lnk in links where lnk.rel.ToLower().Equals("approval_url") select Server.UrlDecode(lnk.href)).FirstOrDefault();
        }

        public async Task<ActionResult> Delete(Guid id)
        {
            var roomOrder = await _roomOrderService.GetAsync(id);

            if (roomOrder != null)
            {
                var model = new RoomOrderModel()
                {
                    Id = roomOrder.Id,
                    Customer = roomOrder.Customer,
                    RoomBooking = new RoomBookingModel()
                    {
                        PartyRoom = roomOrder.RoomBooking.PartyRoom,
                        TimeSlot = roomOrder.RoomBooking.TimeSlot,
                        Date = roomOrder.RoomBooking.Date
                    },
                    PaymentTransaction = roomOrder.PaymentTransaction,
                    Notes = roomOrder.Notes,
                    Total = roomOrder.Total,
                    Status = roomOrder.Status
                };

                return View(model);
            }

            return HttpNotFound();
        }

        [HttpPost]
        public async Task<RedirectToRouteResult> Delete(RoomOrderModel model)
        {
            await _roomOrderService.CancelAsync(model.Id);
            return RedirectToAction("Index");
        }

StirCrazy.Admin/Views/CorporateEvents/Create.cshtml
@model StirCrazy.Admin.Models.Party.CorporateEventModel

@Styles.Render("~/Content/datetimepicker")
@Scripts.Render("~/bundles/datetimepicker")
@Scripts.Render("~/bundles/stircrazy-corporate-booking")

<div class="col-lg-12">
    @using (Html.BeginForm("Create", "CorporateEvents", FormMethod.Post, new { @id = "Availability" }))
    {
        @Html.AntiForgeryToken()

        <!-- DATE/TIME -->
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><h3 class="panel-title"><strong>Corporate</strong> Event</h3></div>
                    <div class="panel-body">
                        <div class="col-md-12">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label><i class="fa fa-calendar"></i>  Choose A Date</label><br />
                                    <div class="col-sm-2">
                                        @Html.TextBoxFor(model => model.Date, "{0:MM/dd/yyyy}", new { @class = "form-control", id = "Schedule", data_format = "MM/DD/YYYY" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row" id="DatePair">
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>From</label>
                                    @Html.TextBoxFor(model => model.StartTime, new { @class = "form-control time start" })
                                </div>
                                <div class="form-group">
                                    <label>Until</label>
                                    @Html.TextBoxFor(model => model.EndTime, new { @class = "form-control time end" })
                                </div>
                                <div class="form-group">
                                    <input type="button" class="btn btn-default" name="Check" value="Check Availability" id="CheckAvailability" />
                                </div>
                                <div class="form-group" id="AvailabilityStatus"></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <div class="ui-checkbox">
                                    <label class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off">
                                        All Day Event
                                        @Html.CheckBoxFor(model => model.IsAllDay)
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><h3 class="panel-title"><strong>Corporate</strong> Information</h3></div>
                    <div class="panel-body">
                        <div class="col-md-5" id="CustomerInformation">
                            <!-- CUSTOMER INFORMATION -->
                            <div class="form-group">
                                <div class="controls">
                                    <label>Company Name</label><br />
                                    @Html.TextBoxFor(model => model.Customer.BusinessName, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="controls">
                                    <label>First Name</label><br />
                                    @Html.TextBoxFor(model => model.Customer.FirstName, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="controls">
                                    <label>Last Name</label><br />
                                    @Html.TextBoxFor(model => model.Customer.LastName, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="controls">
                                    <label>Address</label><br />
                                    @Html.TextBoxFor(model => model.Customer.Address, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="controls">
                                    <label>City</label><br />
                                    @Html.TextBoxFor(model => model.Customer.City, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="controls">
                                    <label>Province</label><br />
                                    <select id="Customer_Province" name="Customer.Province" class="form-control">
                                        <option value="">-- Choose --</option>
                                        <option value="Alberta">Alberta</option>
                                        <option value="British Columbia">British Columbia</option>
                                        <option value="Manitoba">Manitoba</option>
                                        <option value="New Brunswick">New Brunswick</option>
                                        <option value="New Foundland">New Foundland</option>
                                        <option value="Northwest Territories">Northwest Territories</option>
                                        <option value="Nova Scotia">Nova Scotia</option>
                                        <option value="Ontario">Ontario</option>
                                        <option value="Prince Edward Island">Prince Edward Island</option>
                                        <option value="Quebec">Quebec</option>
                                        <option value="Saskatchewan">Saskatchewan</option>
                                        <option value="Yukon Territories">Yukon Territories</option>
                                    </select>                                </div>
                            </div>
                            <div class="form-group">
                                <div class="controls">
                                    <label>Postal Code</label><br />
                                    @Html.TextBoxFor(model => model.Customer.PostalCode, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="controls">
                                    <label>Phone</label><br />
                                    @Html.TextBoxFor(model => model.Customer.PhoneNumber, new { @class = "form-control  bfh-phone" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="controls">
                                    <label>Email</label><br />
                                    @Html.TextBoxFor(model => model.Customer.Email, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="controls">
                                    <label>Total</label><br />
                                    @Html.TextBoxFor(model => model.Total, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="controls">
                                    <label>Special Instructions</label><br />
                                    @Html.TextAreaFor(model => model.Notes, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading"></div>
                    <div class="panel-body">
                        <div class="form-group">
                            <span id="ScheduleResponse" style="display: block"></span>
                            <input type="submit" value="Save & Finish" class="btn btn-default" />
                            @Html.ActionLink("Cancel", "Index", "Room", new { @class = "btn btn-default" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<link href="~/Scripts/plugins/jquery.timepicker/jquery.timepicker.css" type="text/css" rel="stylesheet" />
<script type="text/javascript" src="~/Scripts/plugins/jquery.timepicker/jquery.timepicker.min.js"></script>
<script type="text/javascript" src="~/Scripts/plugins/jquery.datepair/Datepair.js"></script>
<script type="text/javascript" src="~/Scripts/plugins/jquery.datepair/jquery.datepair.js"></script>
<script>

    $('#DatePair .time').timepicker({
        'showDuration': true,
        'timeFormat': 'g:i A'
    });

    $('.time').timepicker('setTime', new Date(0, 0, 0, 0, 0, 0, 0));
    $('#DatePair').datepair();

    $('#IsAllDay').click(function () {
        if ($('#IsAllDay').is(':checked')) {
            $('.time').attr('disabled', 'disabled');
            return;
        }

        $('.time').removeAttr('disabled');
    });
</script>

StirCrazy.Admin/Views/CorporateEvents/Index.cshtml
@using System.Globalization
@using StirCrazy.Core.Utilities
@model IEnumerable<StirCrazy.Admin.Models.Party.CorporateEventModel>
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading bg-dark">
            <h3 class="panel-title"><strong>Corporate</strong> Bookings</h3> <a href="/CorporateEvents/Create" class="btn btn-default btn-rounded btn-sm pull-right"><i class="fa fa-plus"></i> Corporate Booking</a>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 table-responsive filter-right">
                    @if (!Model.Any())
                    {
                        <div class="alert bg-gray-light">
                            It doesn't look like you have any corporate bookings currently.
                            <a href="/CorporateEvents/Create">Create a new corporate booking?</a>
                        </div>
                    }
                    else
                    {
                        <table id="datatable" class="table table-striped table-hover table-dynamic table-dark dataTable">
                            <thead>
                                <tr>
                                    <th>Scheduled</th>
                                    <th>Business</th>
                                    <th>Event</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    var startTime = DateTime.ParseExact(item.StartTime, "HH:mm:ss", CultureInfo.InvariantCulture);
                                    var endTime = DateTime.ParseExact(item.EndTime, "HH:mm:ss", CultureInfo.InvariantCulture);

                                    <tr id="@item.Id">
                                        <td>
                                            @item.Date.ToString("MMM dd, yyyy")
                                        </td>
                                        <td>
                                            @(string.IsNullOrEmpty(item.Customer.BusinessName) ? item.Customer.FullName : item.Customer.BusinessName)
                                        </td>
                                        <td>
                                            @if (item.IsAllDay)
                                            {
                                                @("FULL DAY")
                                            }
                                            else
                                            {
                                                @DateTime.Today.Add(startTime.TimeOfDay).ToString("h:mm tt") @(" - ")
                                                @DateTime.Today.Add(endTime.TimeOfDay).ToString("h:mm tt")
                                            }
                                        </td>
                                        <td>
                                            @item.Status.GetDisplayName()
                                        </td>
                                        <td>
                                            @Html.ActionLink("Details", "Details", new { id = item.Id }) <br />
                                            @Html.ActionLink("Print", "Print", new { id = item.Id }) <br />
                                            @Html.ActionLink("Download", "Save", new { id = item.Id })
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                </div>
            </div>
        </div>
    </div>
</div>